- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Actualizar todos los paquetes a la última versión
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Instalar paquetes del sistema necesarios
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: yes

    - name: Crear directorio para llaves GPG de Docker
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargar la clave GPG oficial de Docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Agregar el repositorio de Docker para Ubuntu
      shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

    - name: Actualizar índice de apt después de agregar el repo
      apt:
        update_cache: yes

    - name: Instalar Docker y sus componentes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Agregar el usuario actual al grupo docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Reiniciar el servicio Docker
      service:
        name: docker
        state: restarted
