services:
#   alloy:
#     image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.8.2}
#     ports:
#       - 12345:12345
#       - 4317:4317
#       - 4318:4318
#     volumes:
#       - ./config.alloy:/etc/alloy/config.alloy
#       - /var/run/docker.sock:/var/run/docker.sock
#     command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

#   cadvisor:
#     image: gcr.io/cadvisor/cadvisor:v0.49.2
#     ports:
#       - "8080:8080"
#     volumes:
#       - /:/rootfs:ro
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - /sys:/sys:ro
#       - /var/lib/docker/:/var/lib/docker:ro
#       - /dev/disk/:/dev/disk:ro
#       - /var/run:/var/run:rw
#     restart: unless-stopped

  loki:
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-3.5.0}
    ports:
      - "3100:3100"
    volumes:
     - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
     - ./tmp/loki:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml


  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v3.4.1}
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    # ports:
    #   - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
      #https://docs.docker.com/engine/daemon/prometheus/
#https://grafana.com/grafana/dashboards/193-docker-monitoring/
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.0.1}
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - 3000:3000/tcp
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards
    entrypoint:
      - sh
      - -euc
      - |
        /run.sh
